# site_url: https://chrisbemister.ca/
# logo_url: https://chrisbemister.ca/img/Logo_color-landscape.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

media_folder: dist/images/uploads
public_folder: /images/uploads

sortable_fields: ['date', 'title', 'category', 'featured']

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'blog'
    label: 'Blog'
    # identifier_field: name
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          default: 'projects',
          options:
            [
              { label: 'Projects', value: 'projects' },
              { label: 'Resources', value: 'resources' },
              { label: 'Interests', value: 'interests' },
              { label: 'Widget', value: 'widget' },
            ],
        }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        max: 3
        min: 0
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  # - name: 'projects'
  #   # identifier_field: name
  #   label: 'Projects'
  #   label_singular: 'Project'
  #   folder: 'assets/content/projects'
  #   create: true
  #   format: 'json'
  #   slug: '{{project_type}}-{{slug}}'
  #   preview_path: 'projects/{{slug}}'
  #   fields:
  #     - {
  #         label: 'Project Type',
  #         name: 'project_type',
  #         widget: 'select',
  #         default: 'Career',
  #         options: [{ label: 'Career', value: 'career' }, { label: 'Personal', value: 'personal' }],
  #       }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
  # - name: 'resources'
  #   # identifier_field: name
  #   label: 'Resources'
  #   label_singular: 'resource'
  #   folder: 'assets/content/resources'
  #   create: true
  #   format: 'json'
  #   slug: '{{resource_type}}-{{slug}}'
  #   preview_path: 'resources/{{slug}}'
  #   fields:
  #     - {
  #         label: 'Resource Type',
  #         name: 'resource_type',
  #         widget: 'select',
  #         default: 'resource',
  #         options:
  #           [
  #             { label: 'Ideas', value: 'ideas' },
  #             { label: 'Technology', value: 'technology' },
  #             { label: 'Expert', value: 'expert' },
  #           ],
  #       }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
  # - name: 'story_projects'
  #   # identifier_field: name
  #   label: 'Story Projects'
  #   label_singular: 'Story Project'
  #   folder: 'assets/content/stories'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'stories/{{slug}}'
  #   # filter: { field: 'project_type', value: 'story' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
  # - name: 'photo_projects'
  #   # identifier_field: name
  #   label: 'Photo Projects'
  #   label_singular: 'Photo Project'
  #   folder: 'assets/content/photos'
  #   create: true
  #   format: 'json'
  #   slug: '{{slug}}'
  #   preview_path: 'photos/{{slug}}'
  #   # filter: { field: 'project_type', value: 'photo' }
  #   fields:
  #     # - { label: 'Project Type', name: 'project_type', widget: 'select', options: ['story', 'photo'] }
  #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  #     - { label: 'Title', name: 'title', widget: 'string' }
  #     - { label: 'Description', name: 'description', widget: 'string', required: false }
  #     - { label: 'Content', name: 'body', widget: 'markdown', required: false }
  #     - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
  #     - {
  #         label: 'Gallery',
  #         name: 'gallery',
  #         widget: 'list',
  #         required: false,
  #         summary: '{{fields.image}}',
  #         field: { label: 'Image', name: 'image', widget: 'image' },
  #       }
